
export const novelContent = {
  title: "Amidza",
  subtitle: "(The Uncle)",
  text: `Within the realm of web design, I delve into the enigmatic story of a historic dwelling that has stood for centuries, concealing a tapestry of secrets, truths, and subtle deceptions. Now, a profound stillness envelops the once-inhabited estate, lingering in anticipation beneath the majestic canopy of towering linden trees, patiently awaiting the return of its youthful occupants.
This grand residence, once a bustling abode for multiple families, boasts a storied past. The ground floor, in days of yore, housed not only living quarters but also stables for horses and modern amenities like bathrooms. Characterized by lofty ceilings and remarkably deep sunken floors, the house's only anomaly is a diminutive iron door that beckons entry into a twilight world of peculiar wonders.
The basement, constructed from imposing stones, stands as a testament to the solidity of the structure. In contrast, the living floor is fashioned from cerpic, a blend of loam and chaff, creating a unique texture. The meticulously cut and carved stones in the basement stand in stark contradistinction to the commonplace earthen floors above, which, over time, succumb to decay, slowly fading away into obscurity.
My most recent foray into the ancestral abode transpired during a visit to my venerable amidza, who still maintained a permanent residence within its timeworn walls. On that occasion, a robust wind swept through, and the sole evidence of vitality emanated from the aged chimney, expelling wisps of smoke into the air. Amidza, engaged in the meticulous task of peeling weathered potatoes for soup, greeted me as I entered.
His once meticulously groomed and neatly trimmed curly black hair had now surrendered to the passage of time, graying gracefully. A peculiar contrast manifested in the fact that his beard remained steadfastly and incongruously black.
"Neno...?" he uttered, almost with a sense of relief, invoking the familiar family moniker. "Come in," he gestured, indicating a chair. "What tidings do you bring this time?" he inquired, drawing the small skemlia closer and settling by the crackling fire. As he opened the shutters, the flickering flames illuminated his countenance, revealing the weariness that time had etched upon him.
"I fear the news is not of the rosiest nature. The military police have commenced evicting residents from their homes, casting them onto the streets without regard for age or health," I conveyed somberly.
As I spoke, he methodically sliced the potatoes, each movement deliberate. Once sliced, the potatoes were meticulously coated with a sparse amount of oil and a sprinkle of salt before finding their place in the oven.
"Dilja?" I inquired with genuine interest.
He nodded in affirmation.
"They've stationed guards at every residence, scrutinizing all who enter or exit with suspicion," I continued in the same measured tone, while he tended to the fire with mašice. Adding another log to the flames, he closed the shutter, and soon, the fire crackled to life. Within the semi-darkened room, an ambiance of domesticity pervaded, mingling with the enticing aroma of baking potatoes. He rose from his seat, retrieved an egg from an ancient kitchen cabinet, presenting it to me with a certain ceremonious flair.
"The neighbor lady," he remarked absentmindedly, breaking the egg over the potatoes before returning the concoction to the oven.

I watched him as he went about the kitchen. His wavy hair, which was always well-groomed, was longer than usual. His sleeves were pulled up carelessly, and his hands, which had always been clean and had perfectly manicured nails, suddenly seemed to be the exact opposite of that picture of him; they were burned and covered in ash residue. When he returned from his long journeys from Europe, Africa to South America, I was a child. He’s learned about people, customs, beliefs, and food throughout these journeys, and kissed odd, alluring foreign women who were waiting for him, somewhere on a stairways of Paris,  Nairobi or Montevideo.
Those were long winter afternoons when I visited him with my father in his luxurious apartment. 
It was snowing, the snow crunched underfoot, and the wind left wonderful ornaments of snowflakes on the windows for who knows who and why. Wearing a white shirt and tie, along with a sweater that always complemented the tie, he always welcomed us immaculately. I had the feeling that he was a man who knew exactly where he belonged. They would gather in the living room, sip on some aged whiskey, and chat while I visited each room in the flat, as each one evoked memories of his travels, primarily focusing on the many books he owned. I would envelop myself in a heavy blanket and sip tea with rum, until I fell asleep. 
And then came the awakening again after a short sweet sleep. I looked at him a little amazed at his appearance: he looked much older than I remembered him. Unsightly long gray hair joined the beard and the only thing that distinguished them was their color. His black old torn sweater, which I remembered from better times, was worn over his bare body.  He left the impression of an old man who was lost in the world of war, who knew so much about other countries' cultures... And when he returned to his homeland, the war began.

Abruptly, I asked him, "What happened to your books?" "I didn't ask many questions when they came to evict me from the residence. I filled a small bag with some clothing. I attempted to grab some cash out of the drawer, but..." One of the soldiers I knew from high school interrupted me, saying, "Leave it with me..." He gave me a cunning grin, anticipating my response, and said, "and you won't need it where you're going anyway."

Despite his friends' laughter, he remained serious.
Well, where am I heading? 

One entire existence appears to have vanished before his eyes in a single instant. He claims he was looking for a hidden secret in his words, which was clearly not there. He stood there, calm, cool, and expressionless. He was simply doing his job. As if we hadn't spent so many years in the same classroom, as if we hadn't shared lunch a thousand times; and worse, when we were in high school, he stood up for me... 
Whispering to himself, he glanced around the apartment and made his way to the exit door. `
}
